### example deployment configuration file
### scf-config-values.yaml

env:
  DOMAIN: cap.suse.ru
  # the UAA prefix is required
  UAA_HOST: uaa.cap.suse.ru
  UAA_PORT: 2793
  GARDEN_ROOTFS_DRIVER: "btrfs"

kube:
  external_ips:
  - 192.168.17.10

  storage_class:
    persistent: "cap-cephfs"

  registry:
    hostname: "registry.suse.com"
    username: ""
    password: ""
  organization: "cap"

secrets:
  # Create a very strong password for user 'admin'
  CLUSTER_ADMIN_PASSWORD: suse1234

  # Create a very strong password, and protect it because it
  # provides root access to everything
  UAA_ADMIN_CLIENT_SECRET: suse1234

enable:
  uaa: true
